version: "3"
services:
  backend:
    image: deepset/haystack-annotation:latest
    environment:
      NODE_ENV: "production"
      DB_HOSTNAME: "somehostname"
      DB_NAME: "someusername"
      DB_USERNAME: "someusername"
      DB_PASSWORD: ""
      # IMPORTANT: please configure credentials with secure strings.
      # DEFAULT_ADMIN_EMAIL: "example@example.com"
      # DEFAULT_ADMIN_PASSWORD: "DEMO_PASSWORD"
      # COOKIE_KEYS: "somesafecookiekeys"
      # JWT_SECRET: "somesafesecret"
      # DOMAIN_WHITELIST: "*"
    ports:
      - "7001:7001"
    links:
      - "db:database"
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: "postgres:15"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: "QA"
    ports:
      - "5433:5432"

    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: "pg_isready --username=somesafeuser --dbname=databasename && psql --username=somesafeuser --list"
      timeout: 3s
      retries: 5
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
